name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: build and test windmill
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout source
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
        name: use nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --workspace
        name: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
        name: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        name: lint